### PR TITLE
Now showing loading indicator when adding subjects and showing error message when something went wrong during saving

### LINKED ISSUE #82: No message if errors occur during subject save
If a user saves his subject while he has (for example) no internet connection, there will obviously be an error. But this error is not appropriately handled by the app. So we should do two things to make it clear for the user what's happening: 
- [ ] add a loading indicator while trying to save subjects
- [ ] show an error message if something went wrong during the subject save process (e.g. if the device has no internet connection)

Also related to #81.

### PR DESCRIPTION
**Pull request by realmayus**
Closes #82

### CODE REVIEW

File: src/components/cards/SubjectCard.tsx [hunk 1]
```diff
@@ -79,14 +83,32 @@ const SubjectCard: React.FC<{
...
   };
   const handleDelete = () => {
+    setLoading('delete');
     apiContext
       .putUserSubjects(
         userContext.user.subjects.filter((s) => s.name !== subject.name)
       )
-      .then(userContext.fetchUserData);
+      .then(userContext.fetchUserData)
+      .then(() => setLoading(null));
```
Comment (Jonasdoubleyou) [inline src/components/cards/SubjectCard.tsx:98]: While you're at it, you could also add error handlers here :)

File: src/api/api.ts [hunk 2]
```diff
@@ -205,9 +205,7 @@ export const axiosPutUserSubjects = async (
   subjects: Subject[]
 ) => {
   const url = `${apiURL}/user/${id}/subjects`;
-  await axios
-    .put(url, subjects, { headers: { token } })
-    .catch(logError('putUserSubjects'));
```
Comment (Jonasdoubleyou) [inline src/api/api.ts:210]: Can we keep this logging on DEV (consistent with all other API requests), or is there a reason to remove it?

Comment (realmayus) [reply src/api/api.ts:210]: Oh, hmm, strange; seems like that was removed when I merged master into it

**Review by Jonasdoubleyou — APPROVED** [review]
